(function () {
  "use strict";
  const JSPDF_URL = "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js";
  let loading;

  function loadPdf() {
    if (window.jspdf && window.jspdf.jsPDF) return Promise.resolve(window.jspdf.jsPDF);
    if (!loading) {
      loading = new Promise((resolve, reject) => {
        const script = document.createElement("script");
        script.src = JSPDF_URL;
        script.onload = () => window.jspdf?.jsPDF ? resolve(window.jspdf.jsPDF) : reject(new Error("PDF library unavailable."));
        script.onerror = () => reject(new Error("Could not load the PDF library."));
        document.head.appendChild(script);
      });
    }
    return loading;
  }

  function date(value) {
    if (!value) return "Not specified";
    try { return new Date(value).toLocaleDateString("en-GB"); } catch { return String(value); }
  }

  async function imageData(url) {
    if (!url) return null;
    if (String(url).startsWith("data:image")) return url;
    try {
      const response = await fetch(url, { mode: "cors" });
      if (!response.ok) return null;
      const blob = await response.blob();
      return await new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => resolve(reader.result);
        reader.onerror = reject;
        reader.readAsDataURL(blob);
      });
    } catch {
      return null;
    }
  }

  function text(contract, signers) {
    const lines = [
      "UK MUSIC RIGHTS AGREEMENT TEMPLATE",
      "",
      `Song: ${contract.song_title || ""}`,
      `Primary artist: ${contract.artist_name || ""}`,
      `Effective date: ${date(contract.effective_date)}`,
      "",
      "DESCRIPTION OF THE MUSICAL WORK",
      contract.description || "",
      "",
      "TERRITORY AND GOVERNING LAW",
      `Territory: ${contract.territory || "Worldwide"}`,
      `Governing law / jurisdiction: ${contract.governing_law || "Not specified"}`,
      "",
      "OWNERSHIP AND REVENUE SPLITS"
    ];
    (signers || []).forEach((signer, index) => {
      lines.push(`${index + 1}. ${signer.name} (${signer.email}) - ${signer.role}`);
      lines.push(`   Master share: ${signer.master_share_percent}% | Publishing share: ${signer.publishing_share_percent}%`);
    });
    lines.push(
      "",
      "GRANT OF RIGHTS AND USE",
      "Each party grants the rights reasonably required to create, reproduce, distribute, communicate to the public, perform, synchronise, promote and exploit the work and recordings within the Territory, subject to the ownership splits above.",
      "",
      "CREDITS AND MORAL RIGHTS",
      "The parties will use reasonable endeavours to provide accurate credits. To the extent permitted by the Copyright, Designs and Patents Act 1988, each party consents to reasonable editing, adaptation and exploitation and waives or agrees not to assert moral rights only to the extent permitted by law.",
      "",
      "ACCOUNTING AND PAYMENT",
      "Unless a written schedule states otherwise, this agreement records ownership percentages only and does not create a promise to pay an advance, fee or royalty. Each party is responsible for registering and collecting its own income and keeping accurate records.",
      "",
      "WARRANTIES, CONFIDENTIALITY, TERM AND TERMINATION",
      "Each party warrants that it has authority to enter this agreement and its contribution does not knowingly infringe another person’s rights. Non-public terms and unreleased materials must be kept confidential. The agreement continues for the life of the rights granted unless the parties agree otherwise in writing; material breach may be grounds for termination.",
      "",
      "GOVERNING LAW AND DISPUTES",
      `This agreement is governed by ${contract.governing_law || "the stated UK jurisdiction"}. The parties will first try in good faith to resolve disputes through discussion or mediation before court proceedings, unless an urgent legal remedy is required.`,
      "",
      "SIGNATURES AND PARTY DETAILS"
    );
    (signers || []).forEach((signer) => {
      lines.push(`${signer.name}`);
      lines.push(`Email: ${signer.email} | Role: ${signer.role}`);
      lines.push(`Master share: ${signer.master_share_percent}% | Publishing share: ${signer.publishing_share_percent}%`);
      lines.push(`Signed name: ${signer.name} | Signed: ${date(signer.signed_at)}`);
    });
    lines.push("", "This is a UK-oriented contract template generated by DabzAudio, not legal advice. The parties should obtain advice from a qualified UK music solicitor before signing or relying on it.");
    return lines.join("\n");
  }

  async function download(contract, signers) {
    const jsPDF = await loadPdf();
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const margin = 18;
    const width = 210 - margin * 2;
    let y = 20;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("DabzAudio Music Contract", margin, y);
    y += 10;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(text(contract, signers), width);
    lines.forEach((line) => {
      if (y > 278) { doc.addPage(); y = 20; }
      doc.text(line, margin, y);
      y += 5;
    });
    for (const signer of signers || []) {
      const signature = await imageData(signer.signature_url);
      if (!signature) continue;
      if (y > 255) { doc.addPage(); y = 20; }
      doc.setFont("helvetica", "bold");
      doc.text(`${signer.name} signature`, margin, y);
      y += 4;
      try {
        doc.addImage(signature, "PNG", margin, y, 55, 22);
        y += 28;
      } catch {
        y += 4;
      }
      doc.setFont("helvetica", "normal");
    }
    const safeName = String(contract.song_title || "music-contract").replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase() || "music-contract";
    doc.save(`${safeName}-completed-contract.pdf`);
  }

  window.LBContractPDF = { download };
})();
