(function () {
  "use strict";
  const JSPDF_URL = "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js";
  let loading;

  function loadPdf() {
    if (window.jspdf && window.jspdf.jsPDF) return Promise.resolve(window.jspdf.jsPDF);
    if (!loading) {
      loading = new Promise((resolve, reject) => {
        const script = document.createElement("script");
        script.src = JSPDF_URL;
        script.onload = () => window.jspdf?.jsPDF ? resolve(window.jspdf.jsPDF) : reject(new Error("PDF library unavailable."));
        script.onerror = () => reject(new Error("Could not load the PDF library."));
        document.head.appendChild(script);
      });
    }
    return loading;
  }

  function date(value) {
    if (!value) return "Not specified";
    try { return new Date(value).toLocaleDateString("en-GB"); } catch { return String(value); }
  }

  function text(contract, signers) {
    const lines = [
      "MUSIC RIGHTS AGREEMENT",
      "",
      `Song: ${contract.song_title || ""}`,
      `Primary artist: ${contract.artist_name || ""}`,
      `Effective date: ${date(contract.effective_date)}`,
      "",
      "DESCRIPTION OF THE MUSICAL WORK",
      contract.description || "",
      "",
      "TERRITORY AND GOVERNING LAW",
      `Territory: ${contract.territory || "Worldwide"}`,
      `Governing law / jurisdiction: ${contract.governing_law || "Not specified"}`,
      "",
      "OWNERSHIP AND REVENUE SPLITS"
    ];
    (signers || []).forEach((signer, index) => {
      lines.push(`${index + 1}. ${signer.name} (${signer.email}) - ${signer.role}`);
      lines.push(`   Master share: ${signer.master_share_percent}% | Publishing share: ${signer.publishing_share_percent}%`);
    });
    lines.push("", "SIGNATURES");
    (signers || []).forEach((signer) => {
      lines.push(`${signer.name}: Signed ${date(signer.signed_at)}`);
    });
    lines.push("", "This completed agreement record was generated by DabzAudio. It is not legal advice.");
    return lines.join("\n");
  }

  async function download(contract, signers) {
    const jsPDF = await loadPdf();
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const margin = 18;
    const width = 210 - margin * 2;
    let y = 20;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("DabzAudio Music Contract", margin, y);
    y += 10;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(text(contract, signers), width);
    lines.forEach((line) => {
      if (y > 278) { doc.addPage(); y = 20; }
      doc.text(line, margin, y);
      y += 5;
    });
    const safeName = String(contract.song_title || "music-contract").replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase() || "music-contract";
    doc.save(`${safeName}-completed-contract.pdf`);
  }

  window.LBContractPDF = { download };
})();
